### ISSUE TITLE
Nuget package with dotnet standard 2.0  generates compilation warning

### ISSUE THREAD

**Issue by hugoterelle** [autofac/Autofac.Wcf#11]
I have a project running dotnet core 2.0 SDK (runtime .NET framework 4.6.1) which references a .net standard library 2.0 
This standard library references Autofac.WCF but at compile time, it raises a warning

Package 'Autofac.Wcf 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	

It doesn't create any problem with my project as my runtime is 4.6.1 but when do you plan to support dotnet standard?

**Comment by tillig** [comment]
WCF services, as they stand today, aren't actually supported in `netstandard 2.0` so there's not an option to target anything but full .NET framework. [Here's the supported API list in `netstandard 2.0`.](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md) Notice System.ServiceModel isn't listed. That's the problem.

They do have [a client-only WCF library for `netstandard`](https://github.com/dotnet/wcf) but it's client-only - there's no service hosting or any of that.

Sooooo long story short, there's nothing we can do. It's up to the framework to support the features before we can target the framework.

**Comment by hugoterelle** [comment]
I understand your point of view, even if I use a WCF client only.

**Comment by tillig** [comment]
The only thing here that helps client implementations [is the `UseWcfSafeRelease` extension](https://github.com/autofac/Autofac.Wcf/blob/develop/src/Autofac.Integration.Wcf/RegistrationExtensions.cs), which is super easy to just copy into your own project... and you're free to do so. It doesn't seem like a lot of value to release a whole separate package (and incur the maintenance, question/answer, breaking change, documentation, support etc. cost) just to push a single extension into a separate package. That extension hasn't changed for well over two years. You're probably safe to just copy/paste it into your own project with little worry that we'd do anything to "improve" or "change" it in any way.

**Comment by hugoterelle** [comment]
Ok thank you for your advices
