### ISSUE TITLE
UseWcfSafeRelease Documentation Incomplete

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [autofac/Autofac.Wcf#14]
The `RegistrationExtensions` method `UseWcfSafeRelease` has incomplete documentation.

It currently reads:

> Dispose the channel instance in such a way that exceptions 

In such a way that exceptions... what? What does it do to exceptions?

**Comment by tillig** [comment]
Oh, nice catch. We'll have to update that.

In the meantime, [check out the actual full docs with examples](http://autofac.readthedocs.io/en/latest/integration/wcf.html) which explains:

> The `UseWcfSafeRelease()` configuration option ensures that exception messages are not lost when disposing client channels.

**Comment by tillig** [comment]
[Fixed.](https://github.com/autofac/Autofac.Wcf/blob/02f1facbc7daec006d9d31f6a62568002f2419f4/src/Autofac.Integration.Wcf/RegistrationExtensions.cs)
