### ISSUE TITLE
.NET Standard compatibility

### ISSUE THREAD

**Issue by alex-training** [autofac/Autofac.Wcf#15]
Hi everyone,

I'm migrating an existing WCF project from .Net Framework 4.6.2 to .Net Standard 2.0

There is a warning:

Package 'Autofac.Wcf 4.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

![wcf](https://user-images.githubusercontent.com/13032219/42231372-6432d332-7eb9-11e8-86a6-dfd39c0ebd95.png)

Are you going to fix the compatibility issue somehow?

**Comment by tillig** [comment]
WCF hosting doesn't exist in .NET Core does it? They have the [client side of things ported](https://github.com/dotnet/wcf) but not the server side, which is what this library is primarily about. Have we missed something?

**Comment by tillig** [comment]
Duplicate #11 

I'm going to close this for now since there's nothing we can do that I'm aware of. However, let us know if they've got the WCF service hosting stuff ported to .NET Core (repo links would help) and we can see what we can do.

**Comment by mustafa-alamir** [comment]
Hi,
What are the alternatives here, if I want to port to .NET Core? Can I replace Autofac.Wcf by something else compatible with .NET Core?
