### ISSUE TITLE
RTE with Autofac 5.1.0

### ISSUE THREAD

**Issue by iksenyuk** [autofac/Autofac.Wcf#21]
I updated Autofac to latest version 5.1.0 and I have run-time error when I resolve service instance from instance context.

System.MissingMethodException: 'Method not found: 'Void Autofac.ResolveRequest..ctor(Autofac.Core.Service, Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)'.'

Everything is working with Autofac 5.0.0.

**Comment by tillig** [comment]
I just published Autofac 5.1.1 and the missing constructor has been put back. Upgrade to that and you should be good to go. Sorry about that!
