### ISSUE TITLE
Targetframework .NEt 4.7.1 instead of 4.7.2?

### ISSUE THREAD

**Issue by rwdd** [autofac/Autofac.Wcf#26]
Would it be possible to build Autofac.Wcf against .NET 4.7.1?

**Comment by tillig** [comment]
Unfortunately not, as .NET 4.7.1. wouldn't support the latest Autofac. [See the release notes here](https://github.com/autofac/Autofac.Wcf/releases/tag/v6.0.0). You can stay on old versions of the packages of you want, or you can build you own fork that supports older .NET.
