### ISSUE TITLE
CS0012 type is not defined in an assembly that is not referenced after installing Autofac.Wcf in brand new WCF Service Application

### ISSUE THREAD

**Issue by yankarinRG** [autofac/Autofac.Wcf#27]
## Describe the Bug

Can't compile because the application startup snippet to init the Autofac Host Factory causes CS0012 type is not defined in an assembly that is not referenced.

## Steps to Reproduce

1. Open Visual Studio 2019
2. Create a new **WCF Service Application** with Target Framework **.NET Framework 4.7.2**
3. Right click on project WcfService1 > Manage Nuget Packages... > Install **Autofac.Wcf** latest stable **6.0.0**
4. Create the **App_Code** folder in the root of the project, and then add the **AppStart.cs** class with the following code:
```c#
using Autofac;
using Autofac.Integration.Wcf;

namespace WcfService1.App_Code
{
    public static class AppStart
    {
        public static void AppInitialize()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<Service1>();
            AutofacHostFactory.Container = builder.Build();
        }
    }
}
```
5. Notice the 3 errors:

- _The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'._
- _The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'._
- _The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'._

## Expected Behavior

No errors and project can compile

## Exception with Stack Trace

None

## Dependency Versions

Autofac: 6.0.0

No other dependencies

## Additional Info

Microsoft Visual Studio Enterprise 2019
Version 16.11.3
VisualStudio.16.Release/16.11.3+31702.278

**Comment by tillig** [comment]
[Pretty sure this is a .NET issue, not Autofac](https://github.com/dotnet/standard/issues/542) since we're targeting `netstandard2.0` and `netstandard2.1`, which .NET 4.7.2 _should_ be working with just fine. However, [apparently there are several things that could cause this issue](https://github.com/dotnet/standard/issues/542#issuecomment-580381317) (none of which are Autofac)...

> Getting the error message on your project is a symptom which may be caused by many different things like for example: Not enabling auto generation of binding redirects, using legacy VS versions to compile, using old-style packages.config instead of PackageReference for your NuGet references, manually adding references to dlls inside a restored NuGet package, etc. That is kind of the reason why you have seen different fixes work for different people, because unfortunately this problem may arise due to different circumstances. That said, the general advise which has worked most of the time is:
>
> - If you can re-target to 4.7.2 or higher, this problem should go away
> - If not, make sure that you:
> - Enable auto-generation of binding redirects. [Link](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection)
> - Migrate your project from packages.config into PackageReference. [Link](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)
> - Make sure you are running on the latest version of Visual Studio. This is because we have added a lot of tooling during the build in order to ensure this problem won't happen.

If you try all that stuff and it's still plaguing you, you may want to follow up [in the issue on .NET that talks about it](https://github.com/dotnet/standard/issues/542) since there's nothing we can do to fix .NET or the tooling to make it work. Sorry.
