### ISSUE TITLE
Autofac v8 compatibility

### ISSUE THREAD

**Issue by 2226cc** [autofac/Autofac.Wcf#33]
## Problem Statement

When using Autofac.Wcf v6.1.0.0 with Autofac v8.0.0.0 the following error occurs on service endpoint call:

Method 'ResolveComponent' in type 'Autofac.Integration.Wcf.AutofacInstanceContext' from assembly 'Autofac.Integration.Wcf, Version=6.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' does not have an implementation.

Reverting back to Autofac v7.1.0.0 resolves this error.
Hence suspecting compatibility issue. Perhaps an interface moved?

I have indeed checked for Autofac.Integration.Wcf.AutofacInstanceContext.ResolveComponent and there is an implementation there.

## Desired Solution

Support for Autofac v8.0.0.0

**Comment by 2226cc** [comment]
To add...

Autofac.ResolveRequest has changed from class to struct.
The IComponentContext.ResolveContext method therefore changed signature to take ResolveRequest struct by reference.

**Comment by alistairjevans** [comment]
@2226cc, are you able you raise a PR to resolve the compatibility?

**Comment by 2226cc** [comment]
Have done a PR for the changes.

PS: sorry if things might be done wrong, not a regular git user. :)

**Comment by tillig** [comment]
Resolved by #34. Will issue a release ASAP.
